site_name: Lerax
site_description: Docs for the Lerax library.
site_author: Theodore Pinkerton
site_url: https://docs.tedpinkerton.ca/lerax

repo_url: https://github.com/Runnersnum40/lerax
repo_name: RunnersNum40/lerax

strict: true

theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - header.autohide
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
